---
driver:
  name: qemu
  memory: 4096
  cpus: 4
  bios: /usr/share/edk2/ovmf/OVMF_CODE.fd
  hostname: kitchen


provisioner:
  name: ansible_playbook
  roles_path: roles
  additional_copy_path: vars
  ansible_verbose: false
  ansible_vault_password_file: .ansible-password.txt
  require_chef_for_busser: false
  hosts: test-kitchen

platforms:
  - name: f42
    driver:
      image: Fedora-KDE.x86_64-42.qcow2
      display: <%= ENV['KDISPLAY'] || 'none' %>

  - name: f43
    driver:
      image: Fedora-KDE.x86_64-43.qcow2
      display: <%= ENV['KDISPLAY'] || 'none' %>

lifecycle:
  post_create:
    - remote: "sudo dnf -y install ansible-collection-community-general python3-passlib"

suites:
  - name: kde

verifier:
  name: shell
  command: >
    py.test -vvvrxXs --color=yes
    --hosts="paramiko://${KITCHEN_USERNAME}@${KITCHEN_HOSTNAME}:${KITCHEN_PORT}?ssh_identity_file=${KITCHEN_SSH_KEY}"
    --sudo test/integration/${KITCHEN_SUITE}
